### ISSUE TITLE
KeyError: 'ms-mcs-admpwd'

### ISSUE THREAD

**Issue by chengteck** [c3c/ADExplorerSnapshot.py#2]
Hi there,

Thanks for the awesome tool!

Happy New Year to you and I hope you have a good 2022 so far!

I encountered the following error when using the tool.

Would you be able to assist on this?

```
└─# python3 ADExplorerSnapshot.py 2Jan2022.dat 
[*] Server: Corp.local
[*] Time of snapshot: 2022-01-02T11:59:17
[*] Mapping offset: XXXXXX
[*] Object count: XXXXXXX
[+] Parsing properties: XXXXXXX
[+] Parsing classes:XXXXXXX
[+] Parsing object offsets: XXXXXXX
[+] Preprocessing objects: XXXXXXX sids, XXXXXXX computers, XXXXXXX domains with XXXXXXX DCs
[▇] Collecting data: 31006/44901 (XXXXXXX users, XXXXXXX groups, XXXXXXX computers, XXXXXXX trusts)
Traceback (most recent call last):
  File "/root/Desktop/Tools/ADExplorerSnapshot.py/ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "/root/Desktop/Tools/ADExplorerSnapshot.py/adexpsnapshot/_init_.py", line 603, in main
    ADExplorerSnapshot(fh, log)
  File "/root/Desktop/Tools/ADExplorerSnapshot.py/adexpsnapshot/_init.py", line 92, in __init_
    self.process()
  File "/root/Desktop/Tools/ADExplorerSnapshot.py/adexpsnapshot/_init_.py", line 158, in process
    ret = fun(obj)
  File "/root/Desktop/Tools/ADExplorerSnapshot.py/adexpsnapshot/_init_.py", line 293, in processComputers
    aces = self.parse_acl(computer, 'computer', ADUtils.get_entry_property(entry, 'nTSecurityDescriptor', raw=True))
  File "/root/Desktop/Tools/ADExplorerSnapshot.py/adexpsnapshot/_init_.py", line 475, in parse_acl
    aces = self._parse_acl_cached(haslaps, entrytype, acl)
  File "/root/Desktop/Tools/ADExplorerSnapshot.py/adexpsnapshot/_init_.py", line 466, in _parse_acl_cached
    _, aces = parse_binary_acl(fake_entry, entrytype, acl, self.objecttype_guid_map)
  File "/root/.local/lib/python3.9/site-packages/bloodhound/enumeration/acls.py", line 142, in parse_binary_acl
    if ace_object.acedata.get_object_type().lower() == objecttype_guid_map['ms-mcs-admpwd']:
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 54, in _getitem_
    return self._store[key.lower()][1]
KeyError: 'ms-mcs-admpwd'
```

**Comment by c3c** [comment]
Hey, in order to see if a potential fix would work, could you replace the following line:

https://github.com/c3c/ADExplorerSnapshot.py/blob/f0c20ccc5184c25d45a2bb1375ea76bd79103c69/adexpsnapshot/__init__.py#L249

with:

```python
props['haslaps'] = (ADUtils.get_entry_property(entry, 'ms-mcs-admpwdexpirationtime', 0) != 0) and ("ms-mcs-admpwd" in self.objecttype_guid_map)
```
I'm not sure yet why this happens. In order for this code path to be reached, `ms-mcs-admpwdexpirationtime` should exist, at which point it's surprising `ms-mcs-admpwd` doesn't exist. This proposed change might incorrectly produce ACL information for the `ReadLAPSPassword` rights.

**Comment by c3c** [comment]
Pushed https://github.com/c3c/ADExplorerSnapshot.py/commit/33708fa990d400ffd0d26d928dab33e66bf1a732 which checks for existence of `ms-mcs-admpwd` first before parsing the ACEs. Please reopen if that didn't solve it.
