### ISSUE TITLE
Script Crashes 

### ISSUE THREAD

**Issue by nickvourd** [c3c/ADExplorerSnapshot.py#35]
Hello I have .dat file (very large .dat file 6.5G). When I am running your tool in the middle of the process, I get the following error. I use python3.10 according to others issues but I do not know what is going wrong. Maybe the size of the file is very large, I don't know. This is my error trace:

[+] Parsing properties: 4058
[+] Parsing classes: 637
[+] Parsing object offsets: 716095
[+] Preprocessing objects: 554340 sids, 136241 computers, 4 domains with 102 DCs
[◢] Collecting data: 25243/716095 (0 users, 0 groups, 0 computers, 90 certtemplates, 4 CAs, 9 trusts)
Traceback (most recent call last):
  File "/usr/src/app/ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "/usr/src/app/adexpsnapshot/__init__.py", line 1129, in main
    ades.outputBloodHound()
  File "/usr/src/app/adexpsnapshot/__init__.py", line 137, in outputBloodHound
    self.process()
  File "/usr/src/app/adexpsnapshot/__init__.py", line 265, in process
    ret = fun(obj)
  File "/usr/src/app/adexpsnapshot/__init__.py", line 651, in processTrusts
    trust = domtrust.to_output()
  File "/usr/local/lib/python3.10/site-packages/bloodhound/ad/trusts.py", line 90, in to_output
    if self.has_flag('WITHIN_FOREST'):
  File "/usr/local/lib/python3.10/site-packages/bloodhound/ad/trusts.py", line 87, in has_flag
    return self.flags & self.trust_flags[flag] == self.trust_flags[flag]
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

**Comment by nickvourd** [comment]
Moreover, I am running the default mode (Bloodhound). Full command: python3.10 ADExplorerSnapshot.py <file>.dat

**Comment by nickvourd** [comment]
Well, I fixed the error here: [BloodHound.py#147](https://github.com/dirkjanm/BloodHound.py/pull/147).
