### ISSUE TITLE
MembershipEnumerator.add_user_properties() missing 1 required positional argument: 'fileNamePrefix'

### ISSUE THREAD

**Issue by helloyw** [c3c/ADExplorerSnapshot.py#36]
└─# python3 ADExplorerSnapshot.py result.dat

[*] Time of snapshot: 2023-12-04T16:10:54
[*] Mapping offset: 0xbffbbc3
[*] Object count: 139228
[+] Parsing properties: 3691
[+] Parsing classes: 543
[+] Parsing object offsets: 139228
[+] Restored pre-processed information from data cache
[◣] Collecting data: 6047/139228 (0 users, 0 groups, 0 computers, 35 certtemplates, 3 CAs, 0 trusts)
Traceback (most recent call last):
  File "/home/kali/desktop/ADExplorerSnapshot.py/ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "/home/kali/desktop/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 1129, in main
    ades.outputBloodHound()
  File "/home/kali/desktop/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 137, in outputBloodHound
    self.process()
  File "/home/kali/desktop/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 265, in process
    ret = fun(obj)
          ^^^^^^^^
  File "/home/kali/desktop/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 744, in processUsers
    MembershipEnumerator.add_user_properties(user, entry)
TypeError: MembershipEnumerator.add_user_properties() missing 1 required positional argument: 'fileNamePrefix'

**Comment by helloyw** [comment]
> found a quickfix, it seems to be related to the new version of bloodhound.py.
> 
> You can edit setup.py and change the bloodhound >= sign to ==
> 
> Credits for this to skelsec

Thank you for your answer, which helped me solve this problem

**Comment by caroline7714** [comment]
hi
I have a similar error to what is displayed below.


https://github.com/c3c/ADExplorerSnapshot.py/issues/38#issue-2025967330

**Comment by DrorDvash** [comment]
> found a quickfix, it seems to be related to the new version of bloodhound.py.
> 
> You can edit setup.py and change the bloodhound >= sign to ==
> 
> Credits for this to skelsec

worked for me also!! thank you!
