### ISSUE TITLE
KeyError: 'Outbound'

### ISSUE THREAD

**Issue by TOMB-RIDER** [c3c/ADExplorerSnapshot.py#59]
python3 ADExplorerSnapshot.py thrth.dat 

[*] Server: 
[*] Time of snapshot: 2024-11-25T18:46:39
[*] Mapping offset: 0x2ad5a3
[*] Object count: 3861
[+] Parsing properties: 1499
[+] Parsing classes: 269
[+] Parsing object offsets: 3861
[+] Preprocessing objects: 320 sids, 5 computers, 1 domains with 1 DCs
[◐] Collecting data: 3579/3861 (3 users, 47 groups, 1 computers, 0 certtemplates, 0 CAs, 0 trusts)
Traceback (most recent call last):
  File "/home/kali/Desktop/v/ADExplorerSnapshot.py/ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "/home/kali/Desktop/v/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 1166, in main
    ades.outputBloodHound()
  File "/home/kali/Desktop/v/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 141, in outputBloodHound
    self.process()
  File "/home/kali/Desktop/v/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 269, in process
    ret = fun(obj)
          ^^^^^^^^
  File "/home/kali/Desktop/v/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 658, in processTrusts
    trust['TrustDirection'] = trust_directions[trust['TrustDirection']]
                              ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Outbound'

**Comment by c3c** [comment]
Duplicate #58
