### ISSUE TITLE
AttributeError: 'Object' object has no attribute 'classes'

### ISSUE THREAD

**Issue by servomekanism** [c3c/ADExplorerSnapshot.py#62]
I installed with:
```
python3 -m venv ~/pyvenvs/adexplorer
source ~/pyvenvs/adexplorer/bin/activate
git clone https://github.com/c3c/ADExplorerSnapshot.py.git
cd ADExplorerSnapshot.py
pip3 install -r requirements.txt
```

The command `pip3 install --user .` does not work for a vanilla debian/kali.

When I run it, i get:
```
(adexplorer) root@kali:ADExplorerSnapshot.py# python3 ADExplorerSnapshot.py /home/user/adsnapshot.dat 
[*] Server: DC1.somewhere.com
[*] Time of snapshot: 2024-12-19T21:07:41
[*] Mapping offset: 0x1aaeaf28
[*] Object count: 86258
[+] Parsing properties: 4121
[+] Parsing classes: 648
[+] Parsing object offsets: 86258
[◣] Preprocessing objects: 5061/86258 (0 sids, 0 computers, 2 domains with 0 DCs)
Traceback (most recent call last):
  File "/root/ADExplorerSnapshot.py/ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 1151, in main
    ades.outputBloodHound()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 129, in outputBloodHound
    self.preprocessCached()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 166, in preprocessCached
    self.preprocess()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 204, in preprocess
    if 'domain' in obj.classes:
                   ^^^^^^^^^^^
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 59, in __getattr__
    return getattr(self._data, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Object' object has no attribute 'classes'
```

**Comment by c3c** [comment]
Duplicate https://github.com/c3c/ADExplorerSnapshot.py/issues/37 
Can you dump some debug data around the location of the error?

Maybe at:
`  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 204, in preprocess`
Add something like this before the if statement:
`print(obj); print(dir(obj))`

Like wise at the following location for `self._data`:
`  File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 59, in __getattr__`

I just pushed a small update to master to get rid of a (non-functional) LRU cache, does that show any new error?

If you're looking for a quick workaround, just add a try-continue:
```
try: 
       if 'domain' in obj.classes:
            ....
except:
      continue
```

**Comment by servomekanism** [comment]
Hello,

1. updating with `git pull` I still get the same error after running it.

2. adding `print(obj)` and `print(dir(obj))` before the `if` at line 204 of `adexpsnapshot/__init__.py`:

```
...
<adexpsnapshot.parser.classes.Object object at 0x7eff6ea4c950>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_data', 'attributes', 'category', 'classes', 'fh', 'fileOffset', 'log', 'raw_attributes', 'snap']
<adexpsnapshot.parser.classes.Object object at 0x7eff6ec93770>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_data', 'attributes', 'category', 'classes', 'fh', 'fileOffset', 'log', 'raw_attributes', 'snap']
<adexpsnapshot.parser.classes.Object object at 0x7eff6ec931a0>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_data', 'attributes', 'category', 'classes', 'fh', 'fileOffset', 'log', 'raw_attributes', 'snap']
<adexpsnapshot.parser.classes.Object object at 0x7eff6ec93800>
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_data', 'attributes', 'category', 'classes', 'fh', 'fileOffset', 'log', 'raw_attributes', 'snap']
Traceback (most recent call last):
  File "/root/ADExplorerSnapshot.py/ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 1153, in main
    ades.outputBloodHound()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 129, in outputBloodHound
    self.preprocessCached()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 166, in preprocessCached
    self.preprocess()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 206, in preprocess
    if 'domain' in obj.classes:
                   ^^^^^^^^^^^
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 59, in __getattr__
    return getattr(self._data, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Object' object has no attribute 'classes'
```

3. adding `print(obj)` and `print(dir(obj))` before the line 59 of `adexpsnapshot/parser/classes.py` does not even start it:
```
Traceback (most recent call last):
  File "/root/ADExplorerSnapshot.py/ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 1149, in main
    ades = ADExplorerSnapshot(args.snapshot, args.output, log)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 42, in __init__
    self.snap.parseHeader()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 270, in parseHeader
    self.header = Header(self)
                  ^^^^^^^^^^^^
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 249, in __init__
    self.server = self.server.rstrip('\x00')
                  ^^^^^^^^^^^
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 59, in __getattr__
    print(obj)
          ^^^
NameError: name 'obj' is not defined
```

4. When applying the workaround at `adexpsnapshot/__init__.py`:
```
[*] Server: DC1.somewhere.com
[*] Time of snapshot: 2024-12-19T21:07:41
[*] Mapping offset: 0x1aaeaf28
[*] Object count: 86258
[+] Parsing properties: 4121
[+] Parsing classes: 648
[+] Parsing object offsets: 86258
[+] Preprocessing objects: 10840 sids, 4057 computers, 2 domains with 3 DCs
[┐] Collecting data: 5037/86258 (0 users, 0 groups, 0 computers, 36 certtemplates, 2 CAs, 0 trusts)
Traceback (most recent call last):
  File "/root/ADExplorerSnapshot.py/ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 1154, in main
    ades.outputBloodHound()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 141, in outputBloodHound
    self.process()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 272, in process
    ret = fun(obj)
          ^^^^^^^^
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 713, in processUsers
    if not (('user' in entry.classes and 'person' == entry.category) or 'msds-groupmanagedserviceaccount' in entry.classes):
                       ^^^^^^^^^^^^^
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 59, in __getattr__
    return getattr(self._data, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Object' object has no attribute 'classes'
```

I made an additional change at line 713 like this (still at `adexpsnapshot/__init__.py`):
```
and make it like this:
    def processUsers(self, entry):
        try:
            if not (('user' in entry.classes and 'person' == entry.category) or 'msds-groupmanagedserviceaccount' in entry.classes):
                return
        except:
            return
```
and it worked.
I am not sure about the quality of the output and whether it's affected though.

**Comment by c3c** [comment]
Thank you, 
on `https://github.com/c3c/ADExplorerSnapshot.py/blob/main/adexpsnapshot/parser/classes.py#L58`
Can you insert `print(self); print(self._data); print(dir(self._data))`
and provide the same context as you did above? (the lines prior to the error happening)

**Comment by c3c** [comment]
It looks like the call to `Object.classes` can swallow exceptions if an `AttributeError` occurs in the `AttributeDict`.
Please `git pull` again, and post any errors printed to the console. However, execution of the script should now succeed.

**Comment by servomekanism** [comment]
Hello again.
Thank you for the prompt fix. It works. Here are the errors printed in the console:
```
(adexplorer) root@kali:ADExplorerSnapshot.py# python3 ADExplorerSnapshot.py /home/user/adsnapshot.dat
[*] Server: DC1.something.com
[*] Time of snapshot: 2024-12-19T21:07:41
[*] Mapping offset: 0x1aaeaf28
[*] Object count: 86258
[+] Parsing properties: 4121
[+] Parsing classes: 648
[+] Parsing object offsets: 86258
[+] Preprocessing objects: 10840 sids, 4057 computers, 2 domains with 3 DCs
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
[+] Collecting data: 145 users, 33 groups, 47 computers, 3 certtemplates, 1 CAs, 1 trusts
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
Error in resolving objectClass:
'AttributeDict' object has no attribute 'log'
[!] Unable to find sid for delegation target: HTTP/192.168.1.12
[!] Unable to find sid for delegation target: HTTP/sth
[!] Unable to find sid for delegation target: REDDS/jierpq.something.com
[!] Unable to find sid for delegation target: http/TwoHHR
[+] Output written to DC1.something.com_1734638861_*.json files
```

**Comment by servomekanism** [comment]
Fixed

**Comment by c3c** [comment]
Thanks, the underlying issue is now also addressed with https://github.com/c3c/ADExplorerSnapshot.py/commit/6fa3dfdb87c2bae3f02f369908afbae2dcacc63a
The `AttributeError` in `AttributeDict` was obscured by the property accessor.
